export SHIMMER_HOST=''


export TIDEPOOL_HOST=''
export TIDEPOOL_UPLOAD_HOST=''

export UPLOADER_LOGIN=''
export UPLOADER_PASSWORD=''
export UPLOADER_USERID=''

export WRITE_ACTIVITY_OBJECTS=true
export MUSSEL_POLL_INTERVAL_MINUTES=15